---
bootstrap:
  - 'main.php'
schema:
  auto_id: true
  loader: phifty/src/Phifty/SchemaLoader.php
  base_model: '\Phifty\Model'
  base_collection: '\Phifty\Collection'
data_sources:
  default:
    driver: mysql
    host: localhost
    database: yourapp
    user: root
    pass: 123123
