---
bootstrap:
  - 'main.php'
schema:
  auto_id: true
  loader: src/Phifty/SchemaLoader.php
  base_model: '\Phifty\Model'
  base_collection: '\Phifty\Collection'
seeds:
  - User::Seed
data_sources:
  default:
    driver: mysql
    host: localhost
    database: phifty
    user: root
    pass: 123123
