---
bootstrap:
  - tests/bootstrap.php
schema:
  auto_id: true
  paths:
   - tests
data_sources:
  default:
    dsn: "mysql:host=localhost;dbname=actionkit_test"
    database: actionkit_test
    user: root
    pass: 
