---
bootstrap:
  - 'main.php'
schema:
  auto_id: true
  loader: src/Phifty/SchemaLoader.php
  base_model: '\Phifty\Model'
  base_collection: '\Phifty\Collection'
data_sources:
  default:
    dsn: 'mysql:host=localhost;dbname=phifty'
    user: phifty
    pass: phifty
